export const WARBONDS = {
  "Helldivers Mobilize":   { color: "#6b7280", label: "Mobilize" },
  "Steeled Veterans":      { color: "#3b82f6", label: "Steeled Vets" },
  "Polar Patriots":        { color: "#06b6d4", label: "Polar Patriots" },
  "Democratic Detonation": { color: "#f97316", label: "Demo Detonation" },
  "Cutting Edge":          { color: "#22d3ee", label: "Cutting Edge" },
  "Truth Enforcers":       { color: "#8b5cf6", label: "Truth Enforcers" },
  "Viper Commandos":       { color: "#22c55e", label: "Viper Commandos" },
  "Freedom's Flame":       { color: "#ef4444", label: "Freedom's Flame" },
  "Servants of Freedom":   { color: "#eab308", label: "Servants of Freedom" },
  "Chemical Agents":       { color: "#84cc16", label: "Chemical Agents" },
  "Urban Legends":         { color: "#ec4899", label: "Urban Legends" },
  "Borderline Justice":    { color: "#f59e0b", label: "Borderline Justice" },
  "Omens of Tyranny":      { color: "#7c3aed", label: "Omens of Tyranny" },
  "Masters of Ceremony":   { color: "#d946ef", label: "Masters of Ceremony" },
  "Force of Law":          { color: "#0ea5e9", label: "Force of Law" },
  "Control Group":         { color: "#14b8a6", label: "Control Group" },
  "Dust Devils":           { color: "#d97706", label: "Dust Devils" },
  "Python Commandos":      { color: "#65a30d", label: "Python Commandos" },
  "Redacted Regiment":     { color: "#475569", label: "Redacted Regiment" },
  "Siege Breakers":        { color: "#dc2626", label: "Siege Breakers" },
  "Entrenched Division":   { color: "#059669", label: "Entrenched Division" },
  "Super Citizen Edition":  { color: "#fbbf24", label: "Super Citizen" },
}

export const WARBOND_ORDER = Object.keys(WARBONDS)
